"""initial schema

Revision ID: 4dfa6e4aea25
Revises: 
Create Date: 2026-03-01 22:54:14.483050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4dfa6e4aea25'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('source_pdf_path', sa.Text(), nullable=False),
    sa.Column('source_pdf_hash', sa.String(length=64), nullable=False),
    sa.Column('mastery_threshold', sa.Float(), nullable=False),
    sa.Column('time_decay_lambda', sa.Float(), nullable=False),
    sa.Column('max_follow_ups_per_session', sa.Integer(), nullable=False),
    sa.Column('topic_radius', sa.Integer(), nullable=False),
    sa.Column('ingestion_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("ingestion_status IN ('pending', 'processing', 'complete', 'failed')", name='chk_ingestion_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_pdf_hash')
    )
    op.create_table('nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('parent_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('child_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('content_chunk_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('application_examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_nodes_course_id', 'nodes', ['course_id'], unique=False)
    op.create_index('idx_nodes_depth', 'nodes', ['course_id', 'depth'], unique=False)
    op.create_table('node_edges',
    sa.Column('parent_id', sa.UUID(), nullable=False),
    sa.Column('child_id', sa.UUID(), nullable=False),
    sa.Column('edge_type', sa.String(length=20), nullable=True),
    sa.CheckConstraint("edge_type IN ('prerequisite', 'related')", name='chk_edge_type'),
    sa.CheckConstraint('parent_id != child_id', name='chk_no_self_loop'),
    sa.ForeignKeyConstraint(['child_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('parent_id', 'child_id')
    )
    op.create_index('idx_node_edges_child', 'node_edges', ['child_id'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('question_type', sa.String(length=20), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('expected_time_seconds', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=10), nullable=False),
    sa.Column('source_chunk_ids', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("difficulty IN ('easy', 'medium', 'hard')", name='chk_difficulty'),
    sa.CheckConstraint("question_type IN ('multiple_choice', 'short_answer')", name='chk_question_type'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_questions_difficulty', 'questions', ['node_id', 'difficulty'], unique=False)
    op.create_index('idx_questions_node_id', 'questions', ['node_id'], unique=False)
    op.create_table('students',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('course_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('current_node_id', sa.UUID(), nullable=True),
    sa.Column('learning_state', sa.String(length=20), nullable=False),
    sa.Column('session_interaction_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("learning_state IN ('baseline', 'learning', 'review', 'exam')", name='chk_learning_state'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['current_node_id'], ['nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_students_course_id', 'students', ['course_id'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('response_time_seconds', sa.Float(), nullable=False),
    sa.Column('attempt_context', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("attempt_context IN ('baseline', 'quiz', 'exam')", name='chk_attempt_context'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_attempts_created_at', 'attempts', ['student_id', 'node_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_attempts_question_id', 'attempts', ['question_id'], unique=False)
    op.create_index('idx_attempts_student_id', 'attempts', ['student_id'], unique=False)
    op.create_index('idx_attempts_student_node', 'attempts', ['student_id', 'node_id'], unique=False)
    op.create_table('student_node_states',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('node_id', sa.UUID(), nullable=False),
    sa.Column('mastery_score', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('teach_completion_score', sa.Float(), nullable=True),
    sa.Column('mistake_classification', postgresql.ARRAY(sa.String(length=30)), nullable=True),
    sa.Column('last_reviewed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_attempts', sa.Integer(), nullable=True),
    sa.Column('correct_attempts', sa.Integer(), nullable=True),
    sa.CheckConstraint('correct_attempts <= total_attempts', name='chk_correct_lte_total'),
    sa.ForeignKeyConstraint(['node_id'], ['nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'node_id')
    )
    op.create_index('idx_sns_mastery', 'student_node_states', ['student_id', 'mastery_score'], unique=False)
    op.create_index('idx_sns_node_id', 'student_node_states', ['node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sns_node_id', table_name='student_node_states')
    op.drop_index('idx_sns_mastery', table_name='student_node_states')
    op.drop_table('student_node_states')
    op.drop_index('idx_attempts_student_node', table_name='attempts')
    op.drop_index('idx_attempts_student_id', table_name='attempts')
    op.drop_index('idx_attempts_question_id', table_name='attempts')
    op.drop_index('idx_attempts_created_at', table_name='attempts')
    op.drop_table('attempts')
    op.drop_index('idx_students_course_id', table_name='students')
    op.drop_table('students')
    op.drop_index('idx_questions_node_id', table_name='questions')
    op.drop_index('idx_questions_difficulty', table_name='questions')
    op.drop_table('questions')
    op.drop_index('idx_node_edges_child', table_name='node_edges')
    op.drop_table('node_edges')
    op.drop_index('idx_nodes_depth', table_name='nodes')
    op.drop_index('idx_nodes_course_id', table_name='nodes')
    op.drop_table('nodes')
    op.drop_table('courses')
    # ### end Alembic commands ###
